language: go
go: 1.11.x
addons:
  apt:
    packages:
    - snapd
env:
- PATH=/snap/bin:$PATH
install:
- sudo snap install snapcraft --classic
script:
  - go build
  - snapcraft
  - snapcraft login --with snap.login
  - snapcraft push --release=edge gohelloworldbabel*.snap
