language: go
go: '1.11.x'
addons:
  apt:
    packages:
      - snapd
env:
  - PATH=/snap/bin:$PATH
before_install:
  - openssl aes-256-cbc -K $encrypted_123abc123_key -iv $encrypted_123abc123_iv -in snap.login.enc -out snap.login -d
install:
  - sudo snap install snapcraft --classic
script: make build
after_success:
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true