name: gohelloworldbabel
version: git
summary: Hello World
description: Hello World!
grade: devel
confinement: strict

parts:
  gohelloworldbabel:
    source: .
    plugin: go
    go-importpath: gohelloworldbabel

apps:
  gohelloworldbabel:
    daemon: simple
    command: gohelloworldbabel
